config/routes.rb
Rails.application.routes.draw do
  get 'restaurants/index'
  get 'restaurants/show'
  get 'restaurants/new'
  get 'restaurants/create'
  get 'reviews/new'
  get 'reviews/create'
  root to: "controller#action"
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates_numericality_of :rating
  validates :content, presence: true
  validates :restaurant, presence: true
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    redirect_to restaurants_path
  end

private

  def restaurant_params
    params(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    @review.save
  end

private

  def review_params
    params(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_navbar_wagon.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="flex-container">
  <%= link_to "Create a new restaurant", restaurants_new_path, class: "btn btn-success" %>
  <div class="row">
    <h1 class= "text-center">Restaurants</h1>
    <% @restaurants.each do |restaurant| %>
    <div class="card col-xs-6 col-md-4">
      <h3 class="card-title"><%= link_to restaurant.name, restaurant_path(restaurant)%></h3>
       <p class="card-text">Address: <%= restaurant.address %></p>
       <p class="card-text">Phone number: <%= restaurant.phone_number %></p>
       <p class="card-text">Category: <%= restaurant.category %></p>
    </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="formular">
  <h1 class="text-center">Add a new restaurant</h1>
  <%= simple_form_for [@restaurant] do |f| %>
    <div class="form-group">
    <%= f.input :name, class: "form-control" %>
    </div>
    <div class="form-group">
    <%= f.input :address, class: "form-control" %>
    </div>
    <div class="form-group">
    <%= f.input :phone_number, class: "form-control" %>
    </div>
    <%= f.submit "add a review", class: "btn btn-primary " %>
  <% end %>
</div>

app/views/restaurants/show.html.erb
<div>
  <h1><%= @restaurant.name %></h1>
  <p>Address: <%=  @restaurant.address %></p>
  <p>Phone number: <%=  @restaurant.phone_number %></p>
  <p>Category: <%=  @restaurant.category %></p>
</div>

<div>
<i class="fas fa-undo"></i> <%= link_to "Back to list", restaurants_path %>
<br>
<br>
<i class="fas fa-edit"></i> <%= link_to "Write review", new_restaurant_review_path(@restaurant, @review) %>
</div>
<br>
<div class="collection-items">
  <h2>Reviews</h2>
  <ul>
    <% @reviews.each do |review| %>
    <li class="collection-item"><div class="rating"><%= "*" * review.rating %></div><div class="review-content"><%= review.content %></div></li>
    <% end %>
  </ul>
</div>

app/views/reviews/new.html.erb
<div class="formular">
  <h1 class="text-center">Write a review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <div class="form-group">
    <%= f.input :content, class: "form-control" %>
    </div>
    <div class="form-group">
    <%= f.input :rating, class: "form-control" %>
    </div>
    <%= f.submit "add a review", class: "btn btn-primary " %>
  <% end %>
</div>